codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    
    patch:
      default:
        target: 75%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true

  ignore:
    - "**/*_test.go"
    - "**/testdata/**"
    - "**/vendor/**"
    - "**/examples/**"
    - "**/build/**"
    - "**/*.pb.go"
    - "**/mocks/**"

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - main
    - develop

github_checks:
  annotations: true